name: CI

on:
  pull_request:
    branches:
      - release # Adjust if your main branch has a different name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Add your build steps here. For example, if you're using Node.js:
      - name: Install dependencies and build
        run: |
          docker build -t nodeapp app
          if [ $? -eq 0 ]; then
            echo "::set-output name=build-success::true"
          else
            echo "::set-output name=build-success::false"
          fi
