name: CI

on:
  pull_request:
    branches:
      - release # Adjust if your main branch has a different name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your build steps here. For example, if you're using Node.js:
      - name: Install dependencies and build
        run: |
          docker build -t nodeapp app

          if [ $? -ne 0 ]; then
            echo "Build failed. Blocking merge and adding comment to pull request."
            # Block merge
            curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -d '{"restrictions": {"users": [], "teams": [], "apps": ["github-actions"]}}' -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}/update-branch-protection
            # Add comment to pull request
            curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -d '{"body": "The build failed. Please fix the issues before merging."}' -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments
            exit 1
          fi
